trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'd8823755-22d5-49e3-a0cc-47a2cbd425b8'
    repository: 'dr1rrb/duplicati-win'
    command: 'build'
    tags: |
      $(Build.BuildId)
      $(duplicati.version)
      latest
