trigger:
- master

variables:
  # The lastest most stable version (as of 2019-06-19, this should be 'beta')
  - group: duplicati-default

  - group: duplicati-stable
  - group: duplicati-beta
  - group: duplicati-experimental
  - group: duplicati-canary

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  displayName: Get config
  inputs:
    filePath: 'azure-pipelines.get-config.ps1'
    failOnStderr: true

- task: RegexReplace@3
  displayName: Generate Dockerfile with the given installer url
  inputs:
    InputSearchPattern: 'Dockerfile'
    FindRegex: '\{duplicati\.install\}'
    ReplaceRegex: '$(duplicati.install)'
    UseUTF8: true

- task: CopyFiles@2
  displayName: Copy Dockerfile to artifacts
  inputs:
    Contents: 'Dockerfile'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Docker file'
    publishLocation: 'Container'

- task: Docker@2
  displayName: Validate that the generated Dockerfile is valid
  inputs:
    containerRegistry: 'd8823755-22d5-49e3-a0cc-47a2cbd425b8'
    repository: 'dr1rrb/duplicati-win'
    command: 'build'
    tags: latest