trigger:
- master

variables:
  # The lastest most stable version (as of 2019-06-19, this should be 'beta')
  - group: duplicati-default

  - group: duplicati-stable
  - group: duplicati-beta
  - group: duplicati-experimental
  - group: duplicati-canary
  
  - name: BuildConfiguration
    value: Release

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  displayName: Get config
  inputs:
    filePath: 'azure-pipelines.get-config.ps1'
    failOnStderr: true


## Crawler ######################################################################
- task: DotNetCoreCLI@2
  displayName: Build crawler
  inputs:
    command: 'pack'
    projects: 'Crawler\DuplicatiCrawler.sln'
    versioningScheme: 'off'

- task: CopyFiles@2
  displayName: Copy crawler to artifacts
  inputs:
    Contents: 'Crawler\DuplicatiCrawler\bin\Release\**\publish\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Crawler'

- task: PublishBuildArtifacts@1
  displayName: Publish crawler artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Crawler'
    ArtifactName: 'Crawler'
    publishLocation: 'Container'


## Docker ######################################################################
- task: RegexReplace@3
  displayName: Generate Dockerfile with the given installer url
  inputs:
    InputSearchPattern: 'Dockerfile'
    FindRegex: '\{duplicati\.install\}'
    ReplaceRegex: '$(duplicati.install)'
    UseUTF8: true

- task: CopyFiles@2
  displayName: Copy Dockerfile to artifacts
  inputs:
    Contents: 'Dockerfile'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Docker'
    
- task: PublishBuildArtifacts@1
  displayName: Publish Dockerfile (and config) artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Docker'
    ArtifactName: 'Docker file'
    publishLocation: 'Container'

# This is the last task as it's the longest, and we don't needs it output
- task: Docker@2
  displayName: Validate that the generated Dockerfile is valid
  inputs:
    containerRegistry: 'd8823755-22d5-49e3-a0cc-47a2cbd425b8'
    repository: 'dr1rrb/duplicati-win'
    command: 'build'
    tags: latest