trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  dockerId: dr1rrb
  imageName: duplicati-win

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'd8823755-22d5-49e3-a0cc-47a2cbd425b8'
    repository: 'duplicati-win'
    command: 'buildAndPush'